name: Build and deploy

on:
  push:
    branches:
      - master

env:
  REACT_APP_CANDY_SHOP_CREATOR_ADDRESS: ${{ secrets.REACT_APP_CANDY_SHOP_CREATOR_ADDRESS }}
  REACT_APP_CANDY_SHOP_TREASURY_MINT: ${{ secrets.REACT_APP_CANDY_SHOP_TREASURY_MINT }}
  REACT_APP_CANDY_SHOP_PROGRAM_ID: ${{ secrets.REACT_APP_CANDY_SHOP_PROGRAM_ID }}
  REACT_APP_SOLANA_NETWORK: ${{ secrets.REACT_APP_SOLANA_NETWORK }}
  REACT_APP_SOLANA_RPC_HOST: ${{ secrets.REACT_APP_SOLANA_RPC_HOST }}
  CI: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: npm install and build
        run: |
          npm install
          npm run build

      - run: |
          zip -r node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - run: |
          unzip node-app.zip
          rm node-app.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "nft-3d-printing"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          package: .
